import { WorkoutDay, Exercise } from './types';

export const presetWorkoutDays: WorkoutDay[] = [
  { id: 'day1', name: 'Chest + Triceps', sortOrder: 1 },
  { id: 'day2', name: 'Back + Biceps', sortOrder: 2 },
  { id: 'day3', name: 'Shoulders + Legs', sortOrder: 3 },
];

export const presetExercises: Exercise[] = [
  // Day 1 - Chest + Triceps
  {
    id: 'ex1',
    workoutDayId: 'day1',
    name: 'Flys',
    muscleTags: ['Chest'],
    isAnchor: false,
    defaultScheme: '3x12-15',
    sortOrder: 1,
  },
  {
    id: 'ex2',
    workoutDayId: 'day1',
    name: 'Incline Dumbbell Press',
    muscleTags: ['Chest', 'Triceps'],
    isAnchor: true,
    defaultScheme: '3x8-12',
    sortOrder: 2,
  },
  {
    id: 'ex3',
    workoutDayId: 'day1',
    name: 'Dips',
    muscleTags: ['Chest', 'Triceps'],
    isAnchor: false,
    defaultScheme: '3x8-12',
    sortOrder: 3,
  },
  {
    id: 'ex4',
    workoutDayId: 'day1',
    name: 'Tricep Pushdown',
    muscleTags: ['Triceps'],
    isAnchor: true,
    defaultScheme: '3x12-15',
    sortOrder: 4,
  },

  // Day 2 - Back + Biceps
  {
    id: 'ex5',
    workoutDayId: 'day2',
    name: 'Neutral Grip Pullups + Straight-arm Pulldowns',
    muscleTags: ['Back', 'Lats'],
    isAnchor: false,
    defaultScheme: '2x8-10',
    notes: 'Prep movement',
    sortOrder: 1,
  },
  {
    id: 'ex6',
    workoutDayId: 'day2',
    name: 'Chin Pulldowns',
    muscleTags: ['Lats'],
    isAnchor: true,
    defaultScheme: '3x10-12',
    notes: 'Focus on lat width',
    sortOrder: 2,
  },
  {
    id: 'ex7',
    workoutDayId: 'day2',
    name: 'Cable Rows',
    muscleTags: ['Back'],
    isAnchor: true,
    defaultScheme: '3x10-12',
    notes: 'Focus on thickness',
    sortOrder: 3,
  },
  {
    id: 'ex8',
    workoutDayId: 'day2',
    name: 'Isolation Pulldowns',
    muscleTags: ['Lats'],
    isAnchor: false,
    defaultScheme: '3x12-15',
    sortOrder: 4,
  },
  {
    id: 'ex9',
    workoutDayId: 'day2',
    name: 'Prone Ys',
    muscleTags: ['Rear Delts', 'Upper Back'],
    isAnchor: false,
    defaultScheme: '2x15-20',
    sortOrder: 5,
  },

  // Day 3 - Shoulders + Legs
  {
    id: 'ex10',
    workoutDayId: 'day3',
    name: 'Incline Curls',
    muscleTags: ['Biceps'],
    isAnchor: true,
    defaultScheme: '3x10-12',
    sortOrder: 1,
  },
  {
    id: 'ex11',
    workoutDayId: 'day3',
    name: 'Shoulder Press Machine',
    muscleTags: ['Shoulders'],
    isAnchor: true,
    defaultScheme: '3x8-12',
    sortOrder: 2,
  },
  {
    id: 'ex12',
    workoutDayId: 'day3',
    name: 'Cable Lateral Raises',
    muscleTags: ['Shoulders'],
    isAnchor: true,
    defaultScheme: '3x12-15',
    sortOrder: 3,
  },
  {
    id: 'ex13',
    workoutDayId: 'day3',
    name: 'Machine-Assisted Lateral Raises',
    muscleTags: ['Shoulders'],
    isAnchor: false,
    defaultScheme: '3x15-20',
    sortOrder: 4,
  },
  {
    id: 'ex14',
    workoutDayId: 'day3',
    name: 'Leg Press',
    muscleTags: ['Legs', 'Quads'],
    isAnchor: false,
    defaultScheme: '3x12-15',
    sortOrder: 5,
  },
  {
    id: 'ex15',
    workoutDayId: 'day3',
    name: 'Leg Extension',
    muscleTags: ['Quads'],
    isAnchor: false,
    defaultScheme: '3x15-20',
    sortOrder: 6,
  },
];
